name: ðŸ’ŽAPI Tests
run-name: Test ${{ github.event.inputs.STAGE }} | ${{ github.event.inputs.MARKER }} marker | ${{ github.event.inputs.THREADS }} threads

on:
  workflow_dispatch:
    inputs:
      STAGE:
        description: 'Choose environment'
        required: true
        default: 'stage'
        type: environment

      MARKER:
        description: 'Marker for pytest'
        required: false
        default: 'smoke'
        type: choice
        options:
          - smoke
          - auth
          - all
          - regression
          - registration

      THREADS:
        description: 'Number of threads for pytest'
        required: false
        default: '1'
        type: choice
        options:
          - '1'
          - '2'
          - '3'
          - '4'
          - '5'

jobs:
  api-tests:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Prepare Allure environment
        run: |
          mkdir -p allure-results
          echo "Branch=${{ github.ref_name }}" > allure-results/environment.properties
          echo "Commit=${{ github.sha }}" >> allure-results/environment.properties
          echo "Stage=${{ secrets.HOST_URL }}" >> allure-results/environment.properties

      - name: Run tests via docker-compose
        env:
          HOST_URL: ${{ secrets.HOST_URL }}
          MARKER: ${{ github.event.inputs.MARKER }}
          THREADS: ${{ github.event.inputs.THREADS }}
        run: |
          docker compose up users-api-test
        
      - name: ðŸ“ ÐšÐ¾Ð¿Ð¸Ñ€ÑƒÐµÐ¼ ÑÑ‚Ð°Ñ€Ñ‹Ðµ Ð»Ð¾Ð³Ð¸
        run: |
          mkdir -p logs/history
          if [ -f "./.github/main/logs/api_requests.log" ]; then
            cp ./.github/main/logs/api_requests.log logs/history/
          fi

      - name: ðŸ“¦ Ð“Ð¾Ñ‚Ð¾Ð²Ð¸Ð¼ Ð½Ð¾Ð²Ñ‹Ðµ Ð»Ð¾Ð³Ð¸
        run: |
          
          cat logs/history/api_requests.log >> logs/api_requests.log || true

      - name: ðŸš€ Ð—Ð°Ð»Ð¸Ð²Ð°ÐµÐ¼ Ð»Ð¾Ð³Ð¸ Ð½Ð° GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: main
          folder: logs
          target-folder: logs
          clean: false

      - name: Copy Allure history
        run: |
          mkdir -p allure-results/history
          if [ -d "./.github/gh-pages/history" ]; then
            cp -R ./.github/gh-pages/history/* allure-results/history/
          fi

      - name: Generate Allure-report
        env:
          HOST_URL: ${{ secrets.HOST_URL }}
          MARKER: ${{ github.event.inputs.MARKER }}
          THREADS: ${{ github.event.inputs.THREADS }}
          CI_COMMIT_REF_NAME: ${{ github.ref_name }}
          CI_COMMIT_SHORT_SHA: ${{ github.sha }}
        run: |
          docker compose up report

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: false